spring.application.name=alucar
server.port=8081

app.cors.allowed-origins=${ALLOWED_ORIGINS:https://meudominio.com}

spring.datasource.url=jdbc:postgresql://localhost:5432/alucar
spring.datasource.username=marcos
spring.datasource.password=admin
spring.sql.init.mode=always

app.jwt.secret=Kx7mPq2vLwZ9rT4nY8sB1cF6hJ3dG5aE0uV+xW==
app.jwt.expiration-ms=86400000