# Nome da aplicação
spring.application.name=alucar

# Porta dinâmica exigida pelo Render (fallback para 10000)
server.port=${PORT:10000}

app.cors.allowed-origins=${CORS_ORIGIN_VAL:https://meudominio.com}

# Configuração de Banco de Dados (usando variáveis de ambiente do Render)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Garantia do Dialeto para evitar erros de metadata no deploy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialização do banco (manter 'never' em produção para segurança)
spring.sql.init.mode=never

# JWT Segredos
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000